# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 21:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecocases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecocase',
            name='user',
        ),
        migrations.AddField(
            model_name='ecocase',
            name='evaluated_by_users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
