# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 02:01
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecocases', '0003_auto_20180317_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonESMEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argumentation', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('ecocase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecocases.Ecocase')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
