# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0005_auto_20180422_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecoeffectpotential',
            old_name='level',
            new_name='title',
        ),
    ]
