# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0006_auto_20180423_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcocaseEval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EcoInnovationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('label', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='ecocaseeval',
            name='eco_innovation_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecocases.EcoInnovationStatus'),
        ),
        migrations.AddField(
            model_name='ecocaseeval',
            name='ecocase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecocases.Ecocase'),
        ),
    ]
