# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 22:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecocases', '0007_auto_20180423_0723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecoeffectpotentialeval',
            old_name='eco_effect_potential',
            new_name='eco_effect_potentials',
        ),
        migrations.AddField(
            model_name='ecocaseeval',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
