# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0008_auto_20180423_2225'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EcocaseEval',
            new_name='EcoinnovationStatusEval',
        ),
    ]
