# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-24 15:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0009_auto_20180423_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environgaineval',
            old_name='environ_gain_level',
            new_name='environ_gain',
        ),
    ]
