# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0011_auto_20180424_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoinnovationstatuseval',
            name='comment',
            field=tinymce.models.HTMLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='ecoinnovationstatuseval',
            name='eco_innovation_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecocases.EcoInnovationStatus'),
        ),
        migrations.AlterField(
            model_name='environgaineval',
            name='environ_gain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecocases.EnvironmentalGain'),
        ),
    ]
