# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0012_auto_20180425_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecoinnovationstatuseval',
            old_name='eco_innovation_status',
            new_name='ecoinnovation_status',
        ),
    ]
