# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0013_auto_20180425_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='esm',
            name='description_en',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='esm',
            name='description',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
    ]
