# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0014_auto_20180522_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esm',
            name='description_en',
        ),
        migrations.AlterField(
            model_name='esm',
            name='description',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
