# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-30 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0016_auto_20180605_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalgain',
            name='color',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
