# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-30 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0019_reboundpotential_reboundpotentialeval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masseffectpotentialeval',
            old_name='masseffectpotential',
            new_name='mass_effect_potential',
        ),
        migrations.RenameField(
            model_name='reboundpotentialeval',
            old_name='reboundpotential',
            new_name='rebound_potential',
        ),
    ]
