# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-30 23:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecocases', '0020_auto_20180630_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcocaseGeneralEval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_inspiring', models.NullBooleanField(default=False)),
                ('social_consequences_comment', tinymce.models.HTMLField(default='', null=True)),
                ('case_characterizations_comments', tinymce.models.HTMLField(default='', null=True)),
                ('ecocase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecocases.Ecocase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
