# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0022_auto_20180630_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecocase',
            name='reference',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
